dataset:
  raw_dir: "data/raw"
  file: "movie_reviews_imdb.csv"
models:
  dir: "models"
  model: "models/sentiment_logreg.pkl"
  extractor: "models/tfidf_extractor.pkl"
  metrics: "models/metrics.txt"
